### ISSUE TITLE
Suggestion: add monoliths back to the game (not the Farlands!)

### ISSUE THREAD

**Issue by Leonardo-Fiori** [Spottedleaf/OldGenerator#1]
Hey man I would love to thank you for the amazing job you did with OldGenerator, works flawlessy 😄 

In the description you are stating that if people have a request for another generator you might look into it. Well, I have one, kinda. It's not an entirely new generator, it's only about adding back to the game an old glitch that was extremely cool: monoliths.

0) first ever video of a monolith https://www.youtube.com/watch?v=ScJztXBgYB4
1) supposition on how it worked https://www.youtube.com/watch?v=T_3pgb4Q6co
2) other suppositions https://www.youtube.com/watch?v=GuXW-Kv_q3g
3) actual value that makes them generate when set to -1 https://www.youtube.com/watch?v=6CjW4pPwtaQ

Would be awesome to use oldgenerator and have monoliths too! Maybe with an higher (or customizable) chance of appearing.. Like a config option (0 to disable 100 to have them literally everywhere)

**Comment by Titaniumtown** [comment]
That would be very interesting.
